package trabalho;

import Controlador.Cadastrocontrolador;
import java.sql.Connection;
import dados.Clientesdados;
import dados.Conexao;
import Modelo.Clientes;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Navas
 */
public class Cadastro extends javax.swing.JFrame {

    private final Cadastrocontrolador controlador;

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        setLocationRelativeTo(null);
        controlador = new Cadastrocontrolador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_cadastro = new javax.swing.JPanel();
        t_nome = new javax.swing.JLabel();
        t_endereco = new javax.swing.JLabel();
        t_telefone = new javax.swing.JLabel();
        t_email = new javax.swing.JLabel();
        b_cadastrar = new javax.swing.JButton();
        c_email = new javax.swing.JTextField();
        c_telefone = new javax.swing.JTextField();
        c_endereco = new javax.swing.JTextField();
        c_nome = new javax.swing.JTextField();
        t_senha1 = new javax.swing.JLabel();
        c_senha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        p_cadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_nome.setForeground(new java.awt.Color(255, 255, 255));
        t_nome.setText("Nome:");
        p_cadastro.add(t_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 62, 30));

        t_endereco.setForeground(new java.awt.Color(255, 255, 255));
        t_endereco.setText("Endereço:");
        p_cadastro.add(t_endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 62, 30));

        t_telefone.setForeground(new java.awt.Color(255, 255, 255));
        t_telefone.setText("Telefone:");
        p_cadastro.add(t_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 62, 30));

        t_email.setForeground(new java.awt.Color(255, 255, 255));
        t_email.setText("Email:");
        p_cadastro.add(t_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 62, 30));

        b_cadastrar.setText("Cadastrar");
        b_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cadastrarActionPerformed(evt);
            }
        });
        p_cadastro.add(b_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 98, 47));

        c_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_emailActionPerformed(evt);
            }
        });
        p_cadastro.add(c_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 340, -1));

        c_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_telefoneActionPerformed(evt);
            }
        });
        p_cadastro.add(c_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 340, -1));

        c_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_enderecoActionPerformed(evt);
            }
        });
        p_cadastro.add(c_endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 340, -1));

        c_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nomeActionPerformed(evt);
            }
        });
        p_cadastro.add(c_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 340, -1));

        t_senha1.setForeground(new java.awt.Color(255, 255, 255));
        t_senha1.setText("Senha");
        p_cadastro.add(t_senha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 62, 30));
        p_cadastro.add(c_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 340, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/moon.png"))); // NOI18N
        p_cadastro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cadastrarActionPerformed
       

        boolean camposPreenchidos = !c_nome.getText().isEmpty() &&
                !c_senha.getText().isEmpty() &&
        !c_endereco.getText().isEmpty() &&
        !c_telefone.getText().isEmpty() &&
        !c_email.getText().isEmpty();

      b_cadastrar.setEnabled(camposPreenchidos);
        
  
controlador.salvaCliente();
   
 
       
    }//GEN-LAST:event_b_cadastrarActionPerformed

    public JTextField getC_email() {
        return c_email;
    }

    public void setC_email(JTextField c_email) {
        this.c_email = c_email;
    }

    public JTextField getC_endereco() {
        return c_endereco;
    }

    public void setC_endereco(JTextField c_endereco) {
        this.c_endereco = c_endereco;
    }

    public JTextField getC_nome() {
        return c_nome;
    }

    public void setC_nome(JTextField c_nome) {
        this.c_nome = c_nome;
    }

    public JTextField getC_senha() {
        return c_senha;
    }

    public void setC_senha(JTextField c_senha) {
        this.c_senha = c_senha;
    }

    public JTextField getC_telefone() {
        return c_telefone;
    }

    public void setC_telefone(JTextField c_telefone) {
        this.c_telefone = c_telefone;
    }

    private void c_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nomeActionPerformed

    private void c_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_enderecoActionPerformed

    private void c_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_telefoneActionPerformed

    private void c_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cadastrar;
    private javax.swing.JTextField c_email;
    private javax.swing.JTextField c_endereco;
    private javax.swing.JTextField c_nome;
    private javax.swing.JTextField c_senha;
    private javax.swing.JTextField c_telefone;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel p_cadastro;
    private javax.swing.JLabel t_email;
    private javax.swing.JLabel t_endereco;
    private javax.swing.JLabel t_nome;
    private javax.swing.JLabel t_senha1;
    private javax.swing.JLabel t_telefone;
    // End of variables declaration//GEN-END:variables

    private String String(char[] password) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
