package trabalho;

import Controlador.LoginControlador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Navas
 */
public class Login extends javax.swing.JFrame {

    private final LoginControlador controlador;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        controlador = new LoginControlador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_login = new javax.swing.JPanel();
        t_login = new javax.swing.JLabel();
        t_senha = new javax.swing.JLabel();
        c_login = new javax.swing.JTextField();
        b_logar = new javax.swing.JButton();
        b_cadastro = new javax.swing.JButton();
        c_senha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        p_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_login.setForeground(new java.awt.Color(255, 255, 255));
        t_login.setText("Login");
        p_login.add(t_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 60, 50));

        t_senha.setForeground(new java.awt.Color(255, 255, 255));
        t_senha.setText("Senha");
        p_login.add(t_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, 37));

        c_login.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        p_login.add(c_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 243, 40));

        b_logar.setText("Logar");
        b_logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_logarActionPerformed(evt);
            }
        });
        p_login.add(b_logar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 171, 41));

        b_cadastro.setText("Cadastro");
        b_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cadastroActionPerformed(evt);
            }
        });
        p_login.add(b_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 171, 50));

        c_senha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        p_login.add(c_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 243, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/moon.png"))); // NOI18N
        p_login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cadastroActionPerformed
        // TODO add your handling code here:
Cadastro teladecadastro = new Cadastro();
        teladecadastro.setVisible(true);
    }//GEN-LAST:event_b_cadastroActionPerformed

    private void b_logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_logarActionPerformed
        try {
            // TODO add your handling code here:
            controlador.autenticador();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_logarActionPerformed



    public JTextField getC_login() {
        return c_login;
    }

    public void setC_login(JTextField c_login) {
        this.c_login = c_login;
    }

    public JTextField getC_senha() {
        return c_senha;
    }

    public void setC_senha(JTextField c_senha) {
        this.c_senha = c_senha;
    }

  

    public void setC_senha(JPasswordField c_senha) {
        this.c_senha = c_senha;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cadastro;
    private javax.swing.JButton b_logar;
    private javax.swing.JTextField c_login;
    private javax.swing.JTextField c_senha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel p_login;
    private javax.swing.JLabel t_login;
    private javax.swing.JLabel t_senha;
    // End of variables declaration//GEN-END:variables
}
